name: Build and Document

on:
  push:
    branches:
      - main


jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: docs
      run: |
        pip install -r requirements.txt    

    - name: Generate Documentation
      run: |
        python3 generate_language_docs.py

    - name: Build HTML
      working-directory: docs
      run: |
        make html
        touch build/html/.nojekyll

    - name: Documentation Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: |
          docs/build/html/*

    - name: Deploy Page
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      if: github.ref == 'refs/heads/main'
      with:
        branch: gh-pages
        folder: docs/build/html # The folder the action should deploy.
